     # Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

  trigger:
  - main

  variables:
  - name: a
    value: 2
  - name: b
    value: 3

  pool:
    vmImage: ubuntu-latest

  stages:
    - stage:
      displayName: Sum for a and b
      jobs:
        - job:
          displayName: Script
          steps:
            - script: |
                Sum=$((${{ variables.a }} + ${{ variables.b }}))
                echo ${{ variables.a }}>tema_faina_script.txt
                echo ${{ variables.b }}>tema_faina_bash.txt
                echo $Sum>tema_faina_script.txt
              displayName: 'Sum using script'
            
            - publish: tema_faina_script.txt
              displayName: Publish artifact
          
        - job:
          displayName: Bash
          steps:
            - bash: |
                Sum = $((${{ variables.a }} + ${{ variables.b }}))
                echo ${{ variables.a }}>tema_faina_script.txt
                echo ${{ variables.b }}>tema_faina_bash.txt
                echo $Sum>tema_faina_bash.txt
              displayName: 'Sum using bash'
            
            - publish: tema_faina_bash.txt
              displayName: Publish artifact for sum using bash
        
        - job:
          displayName: Powershell
          steps:
            - powershell: |
                $Sum = $((${{ variables.a }} + ${{ variables.b }}))
                $Sum>tema_faina_pawershell.txt
                ${{ variables.a }}>tema_faina_pawershell.txt
                ${{ variables.b }}>tema_faina_pawershell.txt
              displayName: 'Sum using powershell'
            
            - publish: tema_faina_pawershell.txt
              displayName: Publish artifact for sum using pawershell