     # Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

  trigger:
  - main

  variables:
  - name: a
    value: 2
  - name: b
    value: 3

  pool:
    vmImage: ubuntu-latest

  stages:
    - stage:
      displayName: Sum for a and b
      jobs:
        - job:
          displayName: Script
          steps:
            - script: |
                S = $((${{ variables.a }} + ${{ variables.b }}))
                echo $S>tema_faina_script.txt
              displayName: 'Sum using script'
            
            - publish: tema_faina_script.txt
              displayName: Publish artifact for sum using script
          
        - job:
          displayName: Bash
          steps:
            - bash: |
                S = $((${{ variables.a }} + ${{ variables.b }}))
                echo $S>tema_faina_bash.txt
              displayName: 'Sum using bash'
            
            - publish: tema_faina_bash.txt
              displayName: Publish artifact for sum using bash